### ISSUE TITLE
Use jumps to change the order of steps being processed

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#16]
AS A Service Manager
I WANT TO define in which order DSL steps should be initiated
SO THAT I could do it without moving whole step blocks within YAML file

Expected output: https://github.com/buerokratt/Ruuter/blob/main/samples/backlog/jumps.md

**Comment by henrikprangelNG** [comment]
"end" is the keyword used to stop DSL service execution

**Comment by henrikprangelNG** [comment]
Linked PR `https://github.com/buerokratt/Ruuter/pull/39` where initial jumping logic was implemented
