### ISSUE TITLE
Use template literals

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#21]
AS A Service Manager
I WANT TO define strings and their concatenations
SO THAT I could use them to describe rules, inputs and outputs within DSL-based services

Expected output: https://github.com/buerokratt/Ruuter/blob/main/samples/backlog/template-literals.md

```
- assign:
    personalCode: 1234567890

- return: ${"PNOEE-" + personalCode}
```
`PNOEE-1234567890`

**Comment by henrikprangelNG** [comment]
During this task, the current js based scripting solution must be validated to be secure - if not, then must be replaced

**Comment by henrikprangelNG** [comment]
Linked PR `https://github.com/buerokratt/Ruuter/pull/40`, since this contains code for js scripting
