### ISSUE TITLE
Define HTTP response codes as acceptable to proceed

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#27]
AS A Service Manager
I WANT acceptable HTTP response codes to proceed to be defined as default settings
SO THAT I shouldn't define them in every DSL step myself and still ensure that all responses with response codes out of this scope are sent to the appropriate endpoint

### Acceptance Criteria
- [x] Allowlist is defined via settings files
- [x] Ruuter stops processing the request the moment it gets a HTTP response code outside of allowlist

Expected output
`http_codes_allowlist: [200, 202]`

**Comment by ewertub** [comment]
This is done within https://github.com/buerokratt/Ruuter/issues/25 and https://github.com/buerokratt/Ruuter/issues/26.
