### ISSUE TITLE
Ruuter won't start if DSLs are invalid

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#34]
AS AN Architect
I WANT TO be sure that Ruuter can only be started if all DSLs are valid
SO THAT I could be sure that the quality of DSLs always corresponds to actual requirements in production level

**Comment by henrikprangelNG** [comment]
@turnerrainer 
Task already done - when an unvalid step is recognized, the application doesn't start. Both the name of the faulty configuration and the faulty step are outputted to console:
